### ISSUE TITLE
Legacy plugin PlayTime v3.1 does not specify an api-version.

### ISSUE THREAD

**Issue by DoodlesEpic** [Twi5TeD/PlayTime#13]
On server startup the paper server throws the following error:
Jul 29 17:33:35 minecraft-server-prod java[4495]: [17:33:35 WARN]: Legacy plugin PlayTime v3.1 does not specify an api-version.

**Comment by Twi5TeD** [comment]
server version?

**Comment by Twi5TeD** [comment]
if its 1.13 + then you can just ignore it all should still work fine :)

**Comment by DoodlesEpic** [comment]
Sure, the server is in Minecraft version 1.17, using the latest paper build (as of today). It would be nice if a fix could be provided though. Thank you very much for the fast response either way :+1:

**Comment by Twi5TeD** [comment]
its a paper feature and not sure it can be removed / fixed but illl look into it

**Comment by ItsLiyua** [comment]
It can be fixed by adding the `api-version`-tag to the version that the plugin is made for. (only "major.minor". Not "major.minor.patch". e.g. "1.18" not "1.18.2")
> This will signal to the server that your plugin has been coded with a specific server version in mind, and that it should not apply any sort of backwards compatibility measures. As a result you will also need to make sure that you have programmed your code to account for reading of older configurations, data, etc... .Each server version can decide how compatibility is achieved, unknown or future versions will prevent the plugin from enabling. As of the 1.14 release, the api-version 1.13 is still allowed - however future versions may drop backwards support based on this version.
([SpigotMC Wiki](https://www.spigotmc.org/wiki/plugin-yml/#optional-attributes))

**Comment by ItsLiyua** [comment]
I don't know if setting a version is a good idea tho because I don't know if this will prevent your plugin from being loaded on newer versions. In the post they said they might remove backwards compatibility for 1.13 so the server might just refuse to load it because it's compatible with a version that old even tho it would technically be compatible with the new versions as well.
If you set it to a newer version it won't be compatible with the older version and every server older than the version you entered will straight up refuse to load your plugin so yeah. You might not wanna set a version.

**Comment by Twi5TeD** [comment]
that is the reason i hadnt  added this as im not sure if it would stop it from working on older versions thanks for the suggestion though.
